spring.resources.static-locations=classpath:templates/

#Define a global max repeated items in protofile like the maximum amount of messages
protofile.max.repeated.items=20

# Application profile: aws, azure or gcp referred to cloud service provider
spring.profiles.default=aws

# Cucumber
cucumber.glue=com.calculator.features
cucumber.features=classpath:features
cucumber.publish.quiet=true