spring.resources.static-locations=classpath:templates/

#To define them go to https://aws.amazon.com/ec2/pricing/on-demand/ and get the values from
# Data Transfer OUT From Amazon EC2 To Internet
# and set them from First 10 TB / Month to Greater than 150 TB / Month
aws.pricing.ec2.rates=0.09, 0.085, 0.07, 0.05 

#Define a global max repeated items in protofile like the maximum amount of messages
protofile.max.repeated.items=20